//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Bettenverwaltung
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class BedException : System.Exception      //Standartexeption der Bettenverwaltung. Wird von versch. Klassen geworfen   
	{                              //und von der View ausgegeben.

        public BedException(String mess) : base(mess)
        {
        }

	}
}

