//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Bettenverwaltung
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using System.Threading;

	public class DBCleaner
	{
		private Thread thread
		{
			get;
			set;
		}

		public virtual BVContext BVContext
		{
			get;
			set;
		}

		public virtual void Start()
		{
			throw new System.NotImplementedException();
		}

		public virtual void Stop()
		{
			throw new System.NotImplementedException();
		}

        public virtual void Clean()
        {
            throw new System.NotImplementedException();
        }

		public DBCleaner()
		{
		}

	}
}

