//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Bettenverwaltung
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Globalization;
    using System.Linq;
    using System.Text;

    public class HistoryItem
    {

        public string text
        {
            get;
            set;
        }
        [Key]
        public int historyItemId
        {
            get;
            set;
        }

        public static HistoryItem CreateEntryItem(int historyItemId)                                    //Ein History-Item für die Patientenaufnahme wird erstellt
        {
            DateTime dat1 = DateTime.Now;
            CultureInfo culture = new CultureInfo("de-DE");     //German Date format
            String patRegisteredText = dat1.ToString("g", culture) + "  :  Patient aufgenommen";
            HistoryItem historyItem = new HistoryItem(historyItemId, patRegisteredText);
            return historyItem;
        }

        public static HistoryItem CreateRelocationItem(int historyItemId, int sourceBed, int destBed)   //Ein History-Item für eine Verlegung wird erstellt
        {
            DateTime dat1 = DateTime.Now;
            CultureInfo culture = new CultureInfo("de-DE");     //German Date format
            String relocText = dat1.ToString("g", culture) + "  :  Verlegung des Patienten von Bett " + sourceBed + " nach Bett " + destBed;
            HistoryItem historyItem = new HistoryItem(historyItemId, relocText);
            return historyItem;
        }

        public HistoryItem()
        {

        }

        public HistoryItem(int id, string text)                                                         //Konstruktor für HistoryItem. Wird nur von den beiden oberen statischen Methoden genutzt.
        {
            this.historyItemId = id;
            this.text = text;//Text und id werden gespeichert sowie die aktuelle Zeit in timestamp.
        }
    }
}

