//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Bettenverwaltung
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Text;

    public class History                                                //Hier wird die Verlegungshistorie des Patienten gespreichert. Jede History Klasse ist einem Patienten zugeordnet.
    {
        [Key]
        public int historyId
        {
            get;
            set;
        }

        public virtual List<HistoryItem> historyItem
        {
            get;
            set;
        }

        /// <summary>
        /// Der History-Eintragmit dem index wird zurückgegeben
        /// </summary>
        /// <param name="index">Index des Eintrages in der Liste</param>
        /// <returns>HistoryItem aus der Liste</returns>
        public virtual HistoryItem GetHistoryItem(int index)            
        {
            return historyItem[index];
        }

        /// <summary>
        /// Die Anzahl der History-Items in der Liste wird zurückgegeben
        /// </summary>
        /// <returns>Größe der historyItemListe</returns>
        public virtual int GetSize()                                    
        {
            return historyItem.Count;
        }

        /// <summary>
        /// Das Angegebene HistroyItem wird hinten in die Liste eingetragen
        /// </summary>
        /// <param name="i">HistoryItem das in die Liste eingefügt werden soll</param>
        public virtual void InsertHistoryItem(HistoryItem i)            
        {
            historyItem.Add(i);
        }

        public History()                
        {
            
        }

        /// <summary>
        /// Ein neues History-Objekt wird angelegt und das Erste History-Item in die Liste eingefügt
        /// </summary>
        /// <returns></returns>
        public static History CreateNewHistory()
        {
            History res = new History();
            res.historyItem = new List<HistoryItem>();
            res.historyItem.Add(Bettenverwaltung.HistoryItem.CreateEntryItem());// für die Patientenaufnahme in die Liste eingefügt.

            return res;
        }
    }
}

