//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Bettenverwaltung
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Text;

    public class History                                                //Hier wird die Verlegungshistorie des Patienten gespreichert. Jede History Klasse ist einem Patienten zugeordnet.
    {
        [Key]
        public int historyId
        {
            get;
            set;
        }

        public virtual List<HistoryItem> historyItem
        {
            get;
            set;
        }

        public virtual HistoryItem GetHistoryItem(int index)            //Der History-Eintragmit dem index wird zurückgegeben
        {
            return historyItem[index];
        }

        public virtual int GetSize()                                    //Die Anzahl der History-Items in der Liste wird zurückgegeben
        {
            return historyItem.Count;
        }

        public virtual void InsertHistoryItem(HistoryItem i)            //Das Angegebene HistroyItem wird hinten in die Liste eingetragen
        {
            historyItem.Add(i);
        }

        public History()                //Ein neues History-Objekt wird angelegt und das Erste History-Item
        {
            historyItem = new List<HistoryItem>();
            this.historyItem.Add(Bettenverwaltung.HistoryItem.CreateEntryItem());//für die Patientenaufnahme in die Liste eingefügt.
        }
    }
}

