//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Bettenverwaltung
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Patient
	{
		private int patId
		{
			get;
			set;
		}

		private string lastname
		{
			get;
			set;
		}

		private string firstname
		{
			get;
			set;
		}

		private DateTime birthday
		{
			get;
			set;
		}

		private bool isFemale
		{
			get;
			set;
		}

		public virtual History History
		{
			get;
			private set;
		}

		public virtual History GetHistory()
		{
			throw new System.NotImplementedException();
		}

		public Patient(string firstname, string lastname, DateTime Birthday, bool isFemale, int patId, int historyId, int historyItemId)
		{
		}

	}
}

