//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Bettenverwaltung
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Text;

    public class Patient                                     //Klasse zum speichern der Patientendaten. Alle Daten könne via getter-Methoden gelesen werden, jedoch nicht geändert werden.
    {
        [Key]
        public int patId
        {
            get;
            set;
        }

        public string lastname
        {
            get;
            set;
        }

        public string firstname
        {
            get;
            set;
        }

        public string birthday
        {
            get;
            set;
        }

        public bool isFemale
        {
            get;
            set;
        }

        public virtual History History
        {
            get;
            set;
        }

        public virtual History GetHistory()
        {
            return this.History;
        }

        public Patient()
        {

        }

        public Patient(string firstname, string lastname, DateTime birthday, bool isFemale, int patId, int historyId, int historyItemId)    //Konstruktor: Der Patient wird aus den Übergabewerten erstellt. Die ID wird aus dem Wert des letzten
        {
            //DB eintrags generiert. Es wird ebenfalls eine neue Historie für den Patienten anglegt.
            this.firstname = firstname;
            this.lastname = lastname;
            this.birthday = birthday.ToString();
            this.isFemale = isFemale;
            this.patId = patId;
            this.History = new History(historyId, historyItemId);
        }
    }
}

