//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Bettenverwaltung
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Controller : IController
	{
		public virtual BVContext BVContext
		{
			get;
			set;
		}

		public virtual IBedView AddPatient(string firstname, string lastname, EStation station, DateTime birthday, bool isFemale)
		{
			throw new System.NotImplementedException();
		}

		public virtual IBedView DismissPatient(int bedId)
		{
			throw new System.NotImplementedException();
		}

		public virtual void AcceptRelocation(int relocationId)
		{
			throw new System.NotImplementedException();
		}

		public virtual IBedView DisplayPatient(int bedId)
		{
			throw new System.NotImplementedException();
		}

		public virtual List<IBedView> SearchPatient(string term)
		{
			throw new System.NotImplementedException();
		}

		public virtual void ConfirmRelocation(int realocationId)
		{
			throw new System.NotImplementedException();
		}

		public virtual void CancelRelocation(int realocationId)
		{
			throw new System.NotImplementedException();
		}

		public virtual List<Relocation> GetActiveRelocationList()
		{
			throw new System.NotImplementedException();
		}

		private Relocation CreateRelocation(int bedId, EStation station)
		{
			throw new System.NotImplementedException();
		}

		public virtual IEnumerable<IBedView> GetBettList()
		{
			throw new System.NotImplementedException();
		}

		private List<Relocation> GetInactiveRelocationList()
		{
			throw new System.NotImplementedException();
		}

		private Bed FindBedFor(Patient p, EStation station)
		{
			throw new System.NotImplementedException();
		}

		private int GetNextHistoryId()
		{
			throw new System.NotImplementedException();
		}

		private int GetNextHistoryItemId()
		{
			throw new System.NotImplementedException();
		}

		private int GetNextRelocationId()
		{
			throw new System.NotImplementedException();
		}

		private int GetNextBedId()
		{
			throw new System.NotImplementedException();
		}

		private int GetNextPatientId()
		{
			throw new System.NotImplementedException();
		}

        private void GetRelocation(int relId)
        {
            throw new System.NotImplementedException();
        }
	}
}

