//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Bettenverwaltung
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Relocation
	{
		private int station
		{
			get;
			set;
		}

		private int relocationId
		{
			get;
			set;
		}

		private bool accepted;

		private DateTime timestamp
		{
			get;
			set;
		}

		public virtual IBedRelocation IBedRelocation
		{
			get;
			set;
		}

		public virtual IBedRelocation IBedRelocation
		{
			get;
			set;
		}

		public Relocation(IBedRelocation bed, EStation station, int relId)
		{
		}

        public virtual void GetStation()
        {
            throw new System.NotImplementedException();
        }

		public virtual void SetActive(IBedRelocation bed)
		{
			throw new System.NotImplementedException();
		}

		public virtual void SetInactive()
		{
			throw new System.NotImplementedException();
		}

		public virtual bool ExecuteRelocation(int historyItemId)
		{
			throw new System.NotImplementedException();
		}

		public virtual bool IsActive()
		{
			throw new System.NotImplementedException();
		}

		public virtual bool IsAccepted()
		{
			throw new System.NotImplementedException();
		}

		public virtual void SetAccepted()
		{
			throw new System.NotImplementedException();
		}

		public virtual IBedView GetSourceBed()
		{
			throw new System.NotImplementedException();
		}

		public virtual IBedView GetDestinationBed()
		{
			throw new System.NotImplementedException();
		}

		public virtual DateTime GetTimestamp()
		{
			throw new System.NotImplementedException();
		}

		public virtual void SetUnaccepted()
		{
			throw new System.NotImplementedException();
		}

		public virtual int GetId()
		{
			throw new System.NotImplementedException();
		}

	}
}

